version: "3.3"

services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx2
    ports:
      - "80:80"
    volumes:
      - .:/docker
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/etc/nginx/logs
    command: [nginx-debug, "-g", "daemon off;"]

  php:
    container_name: php2
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/docker

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 33060:80

  mariadb:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      - MYSQL_DATABASE=study
      - MYSQL_USER=study
      - MYSQL_PASSWORD=12345a,*
      - MYSQL_ROOT_PASSWORD=12345a,*
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
